language: csharp
arch:
  - amd64
os: linux
dist: bionic
language: csharp
mono: none
dotnet: 3.1
solution: SMEIoT.sln

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
    - psql -c "CREATE ROLE smeiot WITH SUPERUSER LOGIN PASSWORD 'smeiot';" -U postgres
    - createdb -T template1 -O smeiot smeiot_test -U postgres
    - sh -c scripts/travis.sh
script:
    - mkdir -p /home/travis/build/ulfjen/SMEIoT/src/SMEIoT.Infrastructure/bin/Debug/netcoreapp3.1/
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test
env:
  - global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=1
