language: csharp
arch:
  - amd64
  - arm64
os: linux
dist: bionic
language: csharp
mono: none
dotnet: 3.1.100
solution: SMEIoT.sln

before_script:
    - sh -c scripts/travis.sh
script:
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test
env:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=1
