language: csharp
sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.0.100
solution: SMEIoT.sln
before_script:
    - mkdir -p out && cd out
    - sudo apt-get install libmosquitto-dev
    - cmake ..
script:
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
