language: csharp
mono: none
sudo: required
dist: xenial
addons:
    snaps:
      - name: dotnet-sdk
        classic: true
        channel: latest/stable
sudo: required
language: csharp
mono: none
install:
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - export PATH="$PATH:$HOME/.local/bin"
script:
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
