language: csharp
arch:
  - amd64
os: linux
dist: bionic
language: csharp
mono: none
dotnet: 3.1
solution: SMEIoT.sln

before_script:
    - sh -c scripts/travis.sh
script:
    - mkdir -p /home/travis/build/ulfjen/SMEIoT/src/SMEIoT.Infrastructure/bin/Debug/netcoreapp3.1/
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test
env:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=1
