language: csharp
sudo: required
dist: xenial
language: csharp
mono: none
dotnet: 3.0.100
solution: SMEIoT.sln
script:
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
